/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sisary.UI;

import com.sisary.clases.ArchivoCliente;
import com.sisary.clases.Conversacion;
import com.sisary.clases.Global;
import com.sisary.clases.Mensaje;
import com.sisary.client.FileClient;
import java.awt.Color;
import java.io.*;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Luis Fernando
 */
public class Interfaz extends javax.swing.JFrame {

    public Interfaz() {
        this.setUndecorated(true);
        initComponents();
        this.setResizable(false);
        this.getContentPane().setBackground(new Color(29, 29, 29));
        this.ChatPanel.setBackground(new Color(29, 29, 29));
        this.LeftPanel.setBackground(new Color(29, 29, 29));
        this.RightPanel.setBackground(new Color(29, 29, 29));

        CustomTitleBar titleBar = new CustomTitleBar(this.Barra, this, "InChat", new Color(29, 29, 29));
        this.setLocationRelativeTo(null);

        this.DireccionIPLabel.setText("Direccion IP: " + Global.usuarioActual.getDireccionIP());
        this.UserNameLabel.setText(Global.usuarioActual.getNombreUsuario());

        this.ButtonCompartirArchivo.setBackground(new Color(0x2cceb7));
        this.ButtonCompartirArchivo.setOpaque(true);
        this.ButtonCompartirArchivo.setBorderPainted(false);
        this.ButtonCompartirArchivo.setFocusPainted(false);
        this.ButtonCompartirArchivo.setContentAreaFilled(true);

        this.ButtonEnviar.setBackground(new Color(0x2cceb7));
        this.ButtonEnviar.setOpaque(true);
        this.ButtonEnviar.setBorderPainted(false);
        this.ButtonEnviar.setFocusPainted(false);
        this.ButtonEnviar.setContentAreaFilled(true);

        this.InputMessage.setBackground(new Color(0x333333));
        this.InputMessage.setForeground(Color.WHITE);
        this.InputMessage.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        this.InputMessage.setFocusTraversalKeysEnabled(true);
        
        this.ScrollUsers.setBorder(new EmptyBorder(0, 0, 0, 0));        
        this.ScrollChats.setBorder(new EmptyBorder(0, 0, 0, 0));
        this.ScrollArchivos.setBorder(new EmptyBorder(0, 0, 0, 0));

        Global.direccionIpExterno = this.LabelDireccionIpExterno;        
        Global.nombreusuarioExterno1 = this.LabelUserExterno;
        Global.nombreusuarioExterno2 = this.LabelUsuarioExterno2;
        Global.scrollUsers = this.ScrollUsers;
        Global.scrollChats = this.ScrollChats;
        Global.scrollArchivos = this.ScrollArchivos;
        Global.updateUsersPanels();

        /*if (Global.usuarioReceptor.equals(null)) {
            this.ButtonCompartirArchivo.setEnabled(false);
            this.ButtonEnviar.setEnabled(false);
            this.InputMessage.setEnabled(false);
        }*/
    }

    private void enviarMensajeAlServidor(String mensaje) {
        try {
            PrintWriter out = new PrintWriter(Global.conexion.getOutputStream(), true);
            out.println(mensaje);
        } catch (IOException e) {
            System.out.println("Error al enviar el mensaje al servidor: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        ScrollUsers = new javax.swing.JScrollPane();
        UserNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DireccionIPLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ChatPanel = new javax.swing.JPanel();
        ScrollChats = new javax.swing.JScrollPane();
        InputMessage = new javax.swing.JTextField();
        ButtonEnviar = new javax.swing.JButton();
        ButtonCompartirArchivo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        LabelUserExterno = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();
        ScrollArchivos = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelUsuarioExterno2 = new javax.swing.JLabel();
        LabelDireccionIpExterno = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Barra = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LeftPanel.setBackground(new java.awt.Color(153, 255, 153));

        UserNameLabel.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        UserNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UserNameLabel.setText("Nombre de Usuario");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        DireccionIPLabel.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        DireccionIPLabel.setForeground(new java.awt.Color(255, 255, 255));
        DireccionIPLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DireccionIPLabel.setText("Direccion IP: ");

        jLabel8.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Usuarios conectados:");

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(UserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DireccionIPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(UserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DireccionIPLabel)
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ChatPanel.setBackground(new java.awt.Color(255, 204, 204));

        ScrollChats.setBackground(new java.awt.Color(51, 51, 51));

        InputMessage.setText("hola");

        ButtonEnviar.setText("Enviar");
        ButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnviarActionPerformed(evt);
            }
        });

        ButtonCompartirArchivo.setText("Archivo");
        ButtonCompartirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCompartirArchivoActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuarioconectado41.png"))); // NOI18N

        LabelUserExterno.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        LabelUserExterno.setForeground(new java.awt.Color(255, 255, 255));
        LabelUserExterno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelUserExterno.setText("Usuario en linea");

        javax.swing.GroupLayout ChatPanelLayout = new javax.swing.GroupLayout(ChatPanel);
        ChatPanel.setLayout(ChatPanelLayout);
        ChatPanelLayout.setHorizontalGroup(
            ChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChatPanelLayout.createSequentialGroup()
                .addGroup(ChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChatPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ScrollChats))
                    .addGroup(ChatPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(InputMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonEnviar)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonCompartirArchivo)
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(ChatPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(LabelUserExterno, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ChatPanelLayout.setVerticalGroup(
            ChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChatPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChatPanelLayout.createSequentialGroup()
                        .addComponent(LabelUserExterno)
                        .addGap(14, 14, 14)))
                .addComponent(ScrollChats, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEnviar)
                    .addComponent(ButtonCompartirArchivo))
                .addGap(28, 28, 28))
        );

        RightPanel.setBackground(new java.awt.Color(102, 51, 255));
        RightPanel.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuarioconectado80.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Archivos del Chat");

        LabelUsuarioExterno2.setFont(new java.awt.Font("Lato Semibold", 1, 14)); // NOI18N
        LabelUsuarioExterno2.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsuarioExterno2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelUsuarioExterno2.setText("Nombre Usuario");

        LabelDireccionIpExterno.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        LabelDireccionIpExterno.setForeground(new java.awt.Color(255, 255, 255));
        LabelDireccionIpExterno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDireccionIpExterno.setText("Direccion IP: ");

        jLabel7.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Archivos");

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(RightPanel);
        RightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPanelLayout.createSequentialGroup()
                        .addComponent(LabelUsuarioExterno2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61))))
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollArchivos)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDireccionIpExterno, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RightPanelLayout.setVerticalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelUsuarioExterno2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelDireccionIpExterno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout BarraLayout = new javax.swing.GroupLayout(Barra);
        Barra.setLayout(BarraLayout);
        BarraLayout.setHorizontalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BarraLayout.setVerticalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Barra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChatPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LeftPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnviarActionPerformed
        String contenidoMensaje = InputMessage.getText();

        if (contenidoMensaje == null || contenidoMensaje.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El mensaje no puede estar vacío.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Conversacion conversacion = Global.getConversacion(Global.usuarioReceptor);
        Mensaje nuevoMensaje = new Mensaje(contenidoMensaje, Global.usuarioActual, Global.usuarioReceptor);

        conversacion.agregarMensaje(nuevoMensaje);
        Global.updateChatPanel(conversacion);

        String mensajeParaServidor = Global.usuarioActual.getNombreUsuario() + ":" + contenidoMensaje + ":" + Global.usuarioReceptor.getNombreUsuario();
        enviarMensajeAlServidor(mensajeParaServidor);

        InputMessage.setText("");
    }//GEN-LAST:event_ButtonEnviarActionPerformed

    private void ButtonCompartirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCompartirArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                 "Archivos permitidos", "txt", "pdf", "docx", "jpg", "jpeg", "png", "gif", "mp3", "wav", "mp4", "avi", "zip", "rar");
        fileChooser.setFileFilter(filter);

        // Mostrar el diálogo de selección de archivos
        int returnValue = fileChooser.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Archivo seleccionado: " + selectedFile.getAbsolutePath());
            FileClient fileClient = new FileClient("192.168.137.1", 12346, selectedFile, Global.usuarioReceptor.getNombreUsuario());

            ArchivoCliente archivoCliente = new ArchivoCliente(Global.usuarioActual.getNombreUsuario(), selectedFile.getName());

            // Agregar el archivo a la lista de archivos en Global
            Global.archivosCliente.add(archivoCliente);

            fileClient.sendFile();
            Global.updateFilesPanels();
        } else {
            System.out.println("Selección de archivo cancelada.");
        }
    }//GEN-LAST:event_ButtonCompartirArchivoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JButton ButtonCompartirArchivo;
    private javax.swing.JButton ButtonEnviar;
    private javax.swing.JPanel ChatPanel;
    private javax.swing.JLabel DireccionIPLabel;
    private javax.swing.JTextField InputMessage;
    private javax.swing.JLabel LabelDireccionIpExterno;
    private javax.swing.JLabel LabelUserExterno;
    private javax.swing.JLabel LabelUsuarioExterno2;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JScrollPane ScrollArchivos;
    private javax.swing.JScrollPane ScrollChats;
    private javax.swing.JScrollPane ScrollUsers;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
